/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.stream.Collectors;

public class App {
    static int inputSize(Scanner scanner) throws Exception {
        int n = -1;
        try {
            n = Integer.parseInt(scanner.nextLine());
            if (n <= 0)
                throw new Exception("Input error. Size <= 0");
        } catch (NumberFormatException ex) {
            System.out.println("Couldn't parse a number. Please, try again");
            n = inputSize(scanner);
        }
        return n;
    }

    static ArrayList<User> inputUsers() throws Exception {

            Scanner scanner = new Scanner(System.in);
            int n = inputSize(scanner);
            ArrayList<User> users = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                try {
                    users.add(new User(scanner.nextLine(), Integer.parseInt(scanner.nextLine())));
                } catch (Exception e) {
                    if (e instanceof NumberFormatException) {
                        System.out.println("Couldn't parse a number. Please, try again");
                    } else {
                        System.out.println(e.getMessage());
                    }
                    --i;
                }

            }
            return users;

    }

    public static void main(String[] args) {
        try{
            ArrayList<User> users = inputUsers();
            ArrayList<String> adultsNames =  users.stream()
                    .filter(user -> user.getAge() >= 18)
                    .map(User::getName)
                    .collect(Collectors.toCollection(ArrayList::new));
            adultsNames.forEach(System.out::println);

        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }

    }
}
