/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Arrays;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
    static int input() throws Exception{
        Scanner scanner = new Scanner(System.in);
        int n = -1;
        try{
            n = Integer.parseInt(scanner.nextLine());
            if (n<=0)
                throw new Exception("Input error. Size <= 0");
        } catch (NumberFormatException ex){
            System.out.println("Couldn't parse a number. Please, try again");
            n = input();
        }
        return n;
    }
    static int[] inputArr() throws Exception{

        Scanner scanner = new Scanner(System.in);
        int n = input();
        int[] arr = new int[n];
        for (int i = 0; i < n; i++) {
            try{
                arr[i]=scanner.nextInt();
            } catch (InputMismatchException ex){
                System.out.println("Couldn't parse a numbers. Please, try again");
                scanner.nextLine();
                i=-1;
            }
        }

        return arr;
    }

    static double avg(int[] arr) throws Exception{
        int cnt=0;
        double sum=0;
        for (int j : arr) {
            if (j < 0) {
                ++cnt;
                sum += j;
            }
        }
        if(cnt==0)
            throw new Exception("There are no negative elements");
        return sum/cnt;
    }

    public static void main(String[] args) {
        try {
            int[] arr = inputArr();
            double a = avg(arr);
            System.out.println(a);
        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}
