/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
    static int input() throws Exception{
        Scanner scanner = new Scanner(System.in);
        int n = -1;
        try{
            n = Integer.parseInt(scanner.nextLine());
            if (n<=0)
                throw new Exception("Input error. Size <= 0");
        } catch (NumberFormatException ex){
            System.out.println("Couldn't parse a number. Please, try again");
            n = input();
        }
        return n;
    }
    static int[] inputArr() throws Exception{

        Scanner scanner = new Scanner(System.in);
        int n = input();
        int[] arr = new int[n];
        for (int i = 0; i < n; i++) {
            try{
                arr[i]=scanner.nextInt();
            } catch (InputMismatchException ex){
                System.out.println("Couldn't parse a numbers. Please, try again");
                scanner.nextLine();
                i=-1;
            }
        }

        return arr;
    }

    static int getFirstDigit(int x){
        int n=x;
        int d=x;
        while(n/10!=0){
            d=n/10;
            n/=10;
        }
        return d;
    }

    static int[] searchNumbers(int[] a) throws Exception{
        int[] b = new int[a.length];
        int k=0;
        for (int j : a) {
            if (j % 10 == getFirstDigit(j)) {
                b[k] = j;
                ++k;
            }
        }
        if(k==0){
            throw new Exception("There are no such elements");
        }
        return b;
    }

    public static void main(String[] args) {
        try{
            int[] a= inputArr();
            int[] b = searchNumbers(a);
            for(int el:b){
                if(el>0)
                    System.out.print(el+" ");
            }
        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
}
