/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

    static int input(){
        Scanner scanner = new Scanner(System.in);
        int n = -1;
        try{
            n = Integer.parseInt(scanner.nextLine());
        } catch (NumberFormatException ex){
            System.out.println("Couldn't parse a number. Please, try again");
            n = input();
        }
        return n;
    }

    static int fib(int n){
        if(n == 0)
            return 0;
        else if(n == 1)
            return 1;
        else
            return fib(n - 1) + fib(n - 2);
    }

    public static void main(String[] args) {
        int n = input();
        try{
            int f = fib(n);
            System.out.println(f);
        } catch (StackOverflowError er){
            System.out.println("Too large number");
        }
    }
}
